---
title: "Économétrie des Séries Temporelles"
author: "Fiche TD #1"
date: "Analyse de Séries Temporelles et Propriétés Stochastiques"
#output: pdf_document
---

### Exercice 1

Soit $X$ une variable aléatoire ayant une distribution avec une moyenne $\mu$ et une variance $\sigma^2$, et soit $Y_t = X$ pour tout $t$.

  (a) Montrez que $\{Y_t\}$ est strictement et faiblement stationnaire.
  (b) Trouvez la fonction d'autocovariance de $\{Y_t\}$.
  (c) Grapher une série de temporelle "typique" de ${Y_t}$.

<br> \bigskip\bigskip

testnamoux 
 
### Exercice 2

Pour chacun des processus suivants, déterminez s'il est :

-   Stationnaire ou non.

-   Un bruit blanc.

-   Une série $\mathsf{iid}$.

-   Une martingale.

  (a) $X_t = \varepsilon_t, \quad \varepsilon_t \sim \mathcal{N}(0, 1), \text{indépendants}.$
  (b) $Z_t = Z_{t-1} + \eta_t, \quad \eta_t \sim \mathcal{N}(0, 1).$
  (c) $W_t = 0.5 W_{t-1} + \xi_t, \quad \xi_t \sim \mathcal{N}(0, 1), \text{indépendants}.$

<br> \bigskip\bigskip

### Exercice 3

Soit $\{\varepsilon_t\}$ un processus de bruit blanc à moyenne nulle. Supposons que le processus observé soit $Y_t = \varepsilon_t + \theta \varepsilon_{t-1}$, où $\theta$ est soit $3$, soit $\frac{1}{3}$.

  (a) Trouvez la fonction d'autocorrélation de $\{Y_t\}$ pour les cas où $\theta = 3$ et $\theta = \frac{1}{3}$. \newline (*Note : Pour déterminer la fonction d'autocorrélation de* $\{Y_t\}$, il est nécessaire de calculer $\mathsf{cov}(Y_t, Y_{t+k})$ pour différentes valeurs de $k$.)

### Exercice 4

Supposons que $\{Y_t\}$ est stationnaire avec une fonction d'autocovariance $\gamma_k$.

  (a) Montrez que $W_t = \Delta Y_t = Y_t - Y_{t - 1}$ est stationnaire en trouvant la moyenne et la fonction d'autocovariance pour $\{ W_t \}$.

  (b) Montrez que $U_t = \Delta^2 Y_t = \Delta[Y_t - Y_{t - 1}] = Y_t - 2 Y_{t - 1} + Y_{t - 2}$ est stationnaire. (*Note : Vous n'avez pas besoin de trouver la moyenne et la fonction d'autocovariance pour $\{U_t\}$*.)

<br> \bigskip\bigskip

### Exercice  5

Supposons que 
\[ Y_t = 5 + 2t + X_t, \]
où $\{X_t\}$ est une série stationnaire de moyenne nulle avec une fonction d'autocovariance $\gamma_k$.

  (a) Trouvez la fonction de moyenne pour $\{Y_t\}$.
  (b) Trouvez la fonction d'autocovariance pour $\{Y_t\}$.
  (c) $\{Y_t\}$ est-elle stationnaire ? Pourquoi ou pourquoi pas ?

